# This is the configuration file for your production environment.
# Serverpod Cloud uses this to determine the public domains.

apiServer:
  port: 8080
  publicHost: butler.api.serverpod.space
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: butler.insights.serverpod.space
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: butler.app.serverpod.space
  publicPort: 443
  publicScheme: https

# Serverpod Cloud manages the database and redis connections.
# These values will likely be overridden by environment variables.
database:
  host: localhost
  port: 5432
  name: butler
  user: postgres
  requireSsl: true

redis:
  enabled: false

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: false
